demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'host.docker.internal') }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      port:  5432
      dbname: "{{ env_var('POSTGRES_DB', 'postgres') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'dbt_demo') }}"
      threads: 1
